const sectorMeans = {
  "Sector 53": 62750000,
  "DLF City Phase 5": 54333330,
  "Sector 54": 52500000,
  "Sector 26": 46666670,
  "Sector 50": 45350000,
  "Sector 28": 44850000,
  "DLF City Phase 1": 40771430,
  "NH 8": 40000000,
  "DLF Golf Course Road": 39166670,
  "Golf course Extension Road": 38300000,
  Other: 25000000,
};

const form = document.querySelector("#valuationForm");
const body = document.body;
const priceOutput = document.querySelector("#priceOutput");
const psfOutput = document.querySelector("#psfOutput");
const sectorOutput = document.querySelector("#sectorOutput");
const profileOutput = document.querySelector("#profileOutput");
const confidenceText = document.querySelector("#confidenceText");
const statusLine = document.querySelector("#statusLine");
const modelMode = document.querySelector("#modelMode");
const areaLabel = document.querySelector("#areaLabel");
const resetButton = document.querySelector("#resetButton");
const themeButton = document.querySelector("#themeButton");
const fullscreenButton = document.querySelector("#fullscreenButton");
const sectorSelect = document.querySelector("#sector");
const marketVisual = document.querySelector("#marketVisual");
const mapLayer = document.querySelector("#mapLayer");
const mapFocusLabel = document.querySelector("#mapFocusLabel");

const formatter = new Intl.NumberFormat("en-IN");
const mapPins = new Map();

const sectorPositions = {
  "NH 8": { x: 18, y: 24, label: "NH8", color: "#f8d265" },
  "Sector 26": { x: 34, y: 30, label: "26", color: "#9be3c9" },
  "DLF City Phase 1": { x: 43, y: 42, label: "P1", color: "#a9c8ec" },
  "Sector 28": { x: 49, y: 29, label: "28", color: "#ffac95" },
  "DLF City Phase 5": { x: 62, y: 43, label: "P5", color: "#f8d265" },
  "DLF Golf Course Road": { x: 70, y: 36, label: "GCR", color: "#9be3c9" },
  "Sector 53": { x: 75, y: 47, label: "53", color: "#ffac95" },
  "Sector 54": { x: 82, y: 39, label: "54", color: "#a9c8ec" },
  "Sector 50": { x: 54, y: 68, label: "50", color: "#f8d265" },
  "Golf course Extension Road": { x: 72, y: 70, label: "GCX", color: "#9be3c9" },
  Other: { x: 30, y: 72, label: "OTH", color: "#c9d3dc" },
};

function getPayload() {
  const data = new FormData(form);
  return {
    sector: data.get("sector"),
    status: data.get("status"),
    transaction: data.get("transaction"),
    bathroom: Number(data.get("bathroom")),
    balcony: Number(data.get("balcony")),
    bedroom: Number(data.get("bedroom")),
    total_area: Number(data.get("total_area")),
  };
}

function formatPrice(value) {
  if (value >= 10000000) {
    return `Rs ${(value / 10000000).toFixed(2)} Cr`;
  }
  return `Rs ${(value / 100000).toFixed(2)} L`;
}

function localEstimate(payload) {
  const sectorValue = sectorMeans[payload.sector] || sectorMeans.Other;
  const areaRatio = payload.total_area / 1500;
  const bedroomFactor = 1 + (payload.bedroom - 3) * 0.065;
  const bathroomFactor = 1 + (payload.bathroom - 3) * 0.028;
  const balconyFactor = 1 + (payload.balcony - 2) * 0.018;
  const statusFactor = payload.status === "Under Construction" ? 0.93 : 1;
  const transactionFactor = payload.transaction === "New Property" ? 1.055 : 1;
  return sectorValue * areaRatio * bedroomFactor * bathroomFactor * balconyFactor * statusFactor * transactionFactor;
}

function tierForSector(sector) {
  const value = sectorMeans[sector] || sectorMeans.Other;
  if (value >= 52000000) return "Prime luxury";
  if (value >= 40000000) return "High premium";
  return "Mid premium";
}

function render(payload, price, source = "fallback") {
  const perSqft = Math.max(price / payload.total_area, 0);
  priceOutput.value = formatPrice(price);
  priceOutput.textContent = formatPrice(price);
  psfOutput.textContent = `Rs ${formatter.format(Math.round(perSqft))}`;
  sectorOutput.textContent = tierForSector(payload.sector);
  profileOutput.textContent = `${payload.bedroom} BHK ${payload.transaction.toLowerCase()}`;
  areaLabel.textContent = `${formatter.format(payload.total_area)} sq ft`;
  confidenceText.textContent =
    payload.status === "Under Construction"
      ? "Construction-stage pricing adjusted against comparable Gurgaon sector listings."
      : "Ready-to-move pricing benchmarked against comparable Gurgaon sector listings.";
  modelMode.textContent = source === "model" ? "Live model" : "Static ready";
  statusLine.textContent =
    source === "model"
      ? "Valuation generated by the deployed scikit-learn pipeline."
      : "Preview estimate shown; deploy on Vercel for live model scoring.";
  setActivePin(payload.sector);
}

async function scoreWithApi(payload) {
  const response = await fetch("/api/predict", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    throw new Error("Prediction API unavailable");
  }

  return response.json();
}

function previewValuation() {
  const payload = getPayload();
  render(payload, localEstimate(payload), "fallback");
  focusSector(payload.sector);
}

async function updateValuation(event) {
  event?.preventDefault();
  const payload = getPayload();
  render(payload, localEstimate(payload), "fallback");

  try {
    statusLine.textContent = "Scoring with live model...";
    const result = await scoreWithApi(payload);
    render(payload, result.predicted_price, "model");
  } catch {
    render(payload, localEstimate(payload), "fallback");
  }
}

function resetForm() {
  form.reset();
  previewValuation();
}

function buildSectorMap() {
  Object.entries(sectorPositions).forEach(([sector, details]) => {
    const pin = document.createElement("button");
    pin.className = "pin";
    pin.type = "button";
    pin.dataset.sector = sector;
    pin.style.left = `${details.x}%`;
    pin.style.top = `${details.y}%`;
    pin.style.background = details.color;
    pin.setAttribute("aria-label", `Select ${sector}`);
    pin.innerHTML = `<span>${details.label}</span>`;
    pin.addEventListener("click", () => {
      sectorSelect.value = sector;
      previewValuation();
    });
    mapPins.set(sector, pin);
    mapLayer.append(pin);
  });
}

function setActivePin(sector) {
  mapPins.forEach((pin, pinSector) => {
    pin.classList.toggle("is-active", pinSector === sector);
  });
  mapFocusLabel.textContent = sector;
}

function focusSector(sector) {
  const details = sectorPositions[sector] || sectorPositions.Other;
  const scale = marketVisual.classList.contains("is-expanded") ? 1.55 : 1.18;
  const xShift = 50 - details.x;
  const yShift = 50 - details.y;
  mapLayer.style.transform = `translate3d(${xShift}%, ${yShift}%, 0) scale(${scale})`;
}

function toggleTheme() {
  const nextTheme = body.dataset.theme === "dark" ? "light" : "dark";
  body.dataset.theme = nextTheme;
  themeButton.setAttribute("aria-label", nextTheme === "dark" ? "Switch to light mode" : "Switch to dark mode");
  localStorage.setItem("preferred-theme", nextTheme);
}

function setInitialTheme() {
  const savedTheme = localStorage.getItem("preferred-theme");
  const systemDark = window.matchMedia?.("(prefers-color-scheme: dark)").matches;
  body.dataset.theme = savedTheme || (systemDark ? "dark" : "light");
}

async function toggleFullscreenMap() {
  const shouldExpand = !marketVisual.classList.contains("is-expanded");

  if (shouldExpand && marketVisual.requestFullscreen) {
    try {
      await marketVisual.requestFullscreen();
    } catch {
      marketVisual.classList.add("is-expanded");
    }
  } else if (!shouldExpand && document.fullscreenElement) {
    await document.exitFullscreen();
  } else {
    marketVisual.classList.toggle("is-expanded", shouldExpand);
  }

  marketVisual.classList.toggle("is-expanded", shouldExpand);
  fullscreenButton.setAttribute(
    "aria-label",
    marketVisual.classList.contains("is-expanded") ? "Collapse sector map" : "Expand sector map",
  );
  focusSector(sectorSelect.value);
}

document.addEventListener("fullscreenchange", () => {
  const isFullscreen = document.fullscreenElement === marketVisual;
  marketVisual.classList.toggle("is-expanded", isFullscreen);
  fullscreenButton.setAttribute("aria-label", isFullscreen ? "Collapse sector map" : "Expand sector map");
  focusSector(sectorSelect.value);
});

form.addEventListener("input", previewValuation);
form.addEventListener("submit", updateValuation);
resetButton.addEventListener("click", resetForm);
themeButton.addEventListener("click", toggleTheme);
fullscreenButton.addEventListener("click", toggleFullscreenMap);

setInitialTheme();
buildSectorMap();
previewValuation();
